### ISSUE TITLE
Create seach by email page

### ISSUE THREAD

**Issue by Coldboltage** [Coldboltage/skyscanner-frontend#3]
Search by email page will allow users to search via their email and see if any references pop up as a result

**MVP** version will be extremely simple.

- User inputs information into input/email box.
- Press submit button
- If the email exists in the database, return references back to user
- If not, show a toast error.

**Tasks** needed completion

- [x] Copy Reference page
- [x] Remove inputs relating to flights
- [x] Create endpoint to search by email
- [x] Build validations
- [x] Show list of references

**Comment by Coldboltage** [comment]
Starting to tackle this issue. Aim to use the reference page and most of its assets.
